# Generated by Django 3.1.2 on 2020-10-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=150)),
                ('time', models.CharField(max_length=150)),
                ('paid', models.BooleanField(default=False)),
                ('left', models.BooleanField(default=False)),
            ],
        ),
    ]
